version: '3.7'

services:
  nginx-rp:
    image: 'nginx:stable-alpine'
    restart: always
    healthcheck:
      test: wget -q 127.0.0.1:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - test
    ports:
      - 80:80
      - 443:443
    logging: &logging
      driver: journald
      options:
        tag: '{{.Name}}'

networks:
  test:
    external:
      name: test_default
