version: '3.7'

services:
  nginx-rp:
    image: 'nginx:stable-alpine'
    restart: always
    healthcheck:
      test: wget -q 0.0.0.0:80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/data:/data/letsencrypt
    networks:
      - test
    ports:
      - 80:80
      - 443:443
    logging: &logging
      driver: journald
      options:
        tag: '{{.Name}}'

networks:
  test:
    external:
      name: test_default
